@baseUrl = http://localhost:3000/api
@resourceName = products

# Categories

# @name getAll
GET {{baseUrl}}/{{resourceName}}

#####

# @name filter
# Lọc sản phẩm 
#gte: greater than or equal (lớn hơn hoặc bằng)
# ?color=silver&price_gte=200 (Lấy ra những product có màu là silver và giá lớn hơn 200)
GET {{baseUrl}}/{{resourceName}}?color=plum&price_gte=200

#####

# @name paginate
# phân trang 
# ?_page=1: thứ tự trang _limit=5: số item có trên mỗi trang
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=5

#####

# @name sort
# Sắp xếp 
# ?_sort=price&_order=asc sắp xếp theo price và sắp xếp tăng dần
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

#####

# @name add
POST {{baseUrl}}/{{resourceName}}
Content-Type:  application/json

{
    "categoryId": "0a26b6d1-1441-4fb6-8e1c-c83f063716e4",
    "name": "Generic Rubber Dog",
    "color": "green",
    "price": 931,
    "description": "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    "thumbnailUrl": "http://placeimg.com/400/400"
}

#####

# @name update
PATCH {{baseUrl}}/{{resourceName}}/gIeLkUr
Content-Type:  application/json

{
    "name": "Generic Rubber Dog Update",
    "color": "blue",
    "price": 1031
}

#####

# @name remove
DELETE {{baseUrl}}/{{resourceName}}/2